# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch

jobs:  
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Build Solution
      run: go build -v ./...
    
    - name: Pull a Podman Container
      run: podman pull docker.io/ubuntu:latest

    - name: Run Podman Container
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: podman run -itd --name tester -e=MONGO_URI="$MONGO_URI" docker.io/ubuntu:latest
